config/routes.rb
Rails.application.routes.draw do


  # Root
  # ----------------------------------------------------------------
  root                        'static_pages#home'


  # Static Pages
  # ----------------------------------------------------------------
  get     'help'          =>  'static_pages#help'
  get     'about'         =>  'static_pages#about'
  get     'contact'       =>  'static_pages#contact'


  # Users
  # ----------------------------------------------------------------
  get     'users/new'
  get     'signup'        =>  'users#new'

  resources :users do
    member do
      get :following, :followers
    end
  end


  # Sessions
  # ----------------------------------------------------------------
  get     'sessions/new'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'
  delete  'logout'        =>  'sessions#destroy'


  # Account Activations
  # ----------------------------------------------------------------
  get 'account_activations/edit'

  resources :account_activations, only: [:edit]


  # Password Resets
  # ----------------------------------------------------------------
  get 'password_resets/new'
  get 'password_resets/edit'

  resources :password_resets, only: [:new, :create, :edit, :update]


  # Microposts
  # ----------------------------------------------------------------

  resources :microposts, only: [:create, :destroy]


  # Relationships
  # ----------------------------------------------------------------

  resources :relationships, only: [:create, :destroy]


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr>
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About",      about_path %></li>
      <li><%= link_to "Contact",    contact_path%></li>
      <li><%= link_to "News",       'http://news.railstutorial.org/' %></li>
    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
            <!-- HOME -->
            <li><%= link_to "Home", root_path %></li>
            <!-- HELP -->
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <!-- USERS -->
              <li><%= link_to "Users", users_path %></li>
              <!-- ACCOUNT DROPDOWN -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <!-- ACCOUNT DROPDOWN MENU -->
                <ul class="dropdown-menu">
                  <!-- PROFILE -->
                  <li><%= link_to "Profile", current_user %></li>
                  <!-- SETTINGS -->
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <!-- LOGOUT -->
                  <li><%= link_to "Sign out", logout_path, method: "delete" %> </li>
                </ul>
              </li>
            <% else %>
                <li><%= link_to "Sign in", login_path %></li>
            <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
    <!-- Include header partial -->
    <%= render 'layouts/header' %>
    <div class="container">
      <!-- Flash Messages -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>


        <%= yield %>
        <!-- Include footer partial -->
        <%= render 'layouts/footer' %>
        <!-- Display debugging tools if in development environment -->
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>